<?php
      // Cave menu dropdown
         echo '<select class="select_cave" name="cave_ID">';                      
         echo '<option value="">ALL</option>';                    
         echo '<option value="1">1</option>';                    
         echo '<option value="2">2</option>';                    
         echo '<option value="3">3</option>';                    
         echo '<option value="4">4</option>';                    
         echo '<option value="5">5</option>';                    
         echo '<option value="6">6</option>';                    
         echo '<option value="7">7</option>';                    
         echo '<option value="8">8</option>';                    
         echo '<option value="9">9</option>';                    
         echo '<option value="10">10</option>';                    
         echo '<option value="11">11</option>';                    
         echo '<option value="12">12</option>';                    
         echo '<option value="13">13</option>';                    
         echo '<option value="14">14</option>';                    
         echo '<option value="15">15</option>';                    
         echo '<option value="16">16</option>';                    
         echo '<option value="17">17</option>';                    
         echo '<option value="18">18</option>';                    
         echo '<option value="19">19</option>';                    
         echo '<option value="20">20</option>';                    
//         echo '<option value="120">20A</option>';                    
         echo '<option value="21">21</option>';                    
         echo '<option value="22">22</option>';                    
//         echo '<option value="221">22A</option>';                    
         echo '<option value="23">23</option>';                    
         echo '<option value="24">24</option>';                    
//         echo '<option value="124">24A</option>';                    
         echo '<option value="25">25</option>';                    
         echo '<option value="26">26</option>';                    
         echo '<option value="27">27</option>';                    
         echo '<option value="28">28</option>';                    
         echo '<option value="29">29</option>';                    
         echo '<option value="30">30</option>';                    
//         echo '<option value="130">30A</option>';                    
         echo '<option value="31">31</option>';                    
         echo '<option value="32">32</option>';                    
//         echo '<option value="132">32 Yadavas</option>';
         echo '<option value="33">33</option>';                    
         echo '<option value="34">34</option>';                    
//         echo '<option value="101">Ganeshaleni</option>';
//         echo '<option value="102">Jogeshwari</option>';  
//         echo '<option value="100">Misc</option>';
         echo '</select>';                         
?>